apiVersion: v1
kind: ResourceQuota
metadata:
  name: researcher-quota
  namespace: researcher-dev
spec:
  hard:
    requests.cpu: "20"
    requests.memory: "64Gi"
    limits.cpu: "20"
    limits.memory: "64Gi"
    requests.storage: "7Ti"
    persistentvolumeclaims: "10"
    services: "5"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: researcher-limits
  namespace: researcher-dev
spec:
  limits:
  - default:
      cpu: "20"
      memory: "64Gi"
    defaultRequest:
      cpu: "10"
      memory: "32Gi"
    type: Container
  - default:
      cpu: "20"
      memory: "64Gi"
    defaultRequest:
      cpu: "10"
      memory: "32Gi"
    type: Pod 