apiVersion: batch/v1
kind: Job
metadata:
  name: simulation-job
  namespace: researcher-dev
  labels:
    app: simulation
    type: batch-job
spec:
  priorityClassName: simulation-priority-normal
  parallelism: 1
  completions: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: simulation
        type: batch-job
    spec:
      containers:
      - name: simulation-container
        image: simulation:latest
        resources:
          requests:
            cpu: "20"
            memory: "64Gi"
          limits:
            cpu: "20"
            memory: "64Gi"
        volumeMounts:
        - name: simulation-data
          mountPath: /data
        - name: simulation-results
          mountPath: /results
        env:
        - name: SIMULATION_TYPE
          value: "research-simulation"
        - name: MAX_RUNTIME
          value: "10800"  # 3시간 (초 단위)
        command: ["/bin/bash"]
        args: ["-c", "python /app/run_simulation.py --input /data --output /results"]
      volumes:
      - name: simulation-data
        persistentVolumeClaim:
          claimName: simulation-data-pvc
      - name: simulation-results
        persistentVolumeClaim:
          claimName: simulation-results-pvc
      restartPolicy: Never
      nodeSelector:
        node-type: work-node
      tolerations:
      - key: "workload-type"
        operator: "Equal"
        value: "simulation"
        effect: "NoSchedule" 